sudo: false
language: node_js
node_js:
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '10'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: JQoWNqH45gWc4ik3N2srGystZSwa6eQVSqJc19aiury5DdzEq6v/apXZ5FW4uKfDqe4p+hP1ww3BGbv9wF6WVZ3fJfqfM8hqLxP7r26OoCInAP4UeTUJaklqwLhXMTVlD/i4wNxrgo2idUzM2JgRFy0A9uVbvVNa/D1t5gSYYLY=
  email:
    recipients:
      secure: Gl6tmNY6KTCjuM3usU4Np0qt9cD/UsrBItNjBP0GvnGxQ1LJy52tbJvu1hlmM+MycxA2kVvv4dTFKjcJgZcVmkKoQy0OO6LklhPgfjDBwke9bdmIaLPab6fusC5zNBnnEMti/9N/kTQ6IHbqJRhVRiJZPxOVY3vGS9AMc5zDoFQ=
